### ISSUE TITLE
Loader Failed

### ISSUE THREAD

**Issue by angelsky02** [elements-gaming/elementszo#1]
![Desktop Screenshot 2023 07 13 - 02 45 00 19](https://github.com/elements-gaming/elementszo/assets/139445683/c850c56d-e9be-4266-aa5a-e52932b9a3ac)

**Comment by egn2020** [comment]
Go to our website download page and download VISUAL C++ 2010 and install. If already installed or error go to your control panel go to program and features and uninstall microsoft visual c++ 2010 and install VISUAL C++ 2010 you download it from our website.

**Comment by angelsky02** [comment]
Ok thank you for the answer I will do it
